version: '3.1'

services:

  #service name
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'app_matomo'
      # You can use whatever password you like
      MYSQL_PASSWORD: '123456789'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '123456789'
    volumes:
      - ./mysql:/var/lib/mysql

  #service name
  app_matomo:
    image: matomo:3.9.1
    restart: always
    links:
      - db
    ports:
      - "80:80"
    volumes:
      - ./matomo_config:/var/www/html/config
      - ./matomo_logs:/var/www/html/logs

  #service name
  webserver:
    image: 'bitnami/apache:latest'
    ports:
      - 443:8080
    volumes:
      - ./website/:/app
